/**
 * 3gpp-analyticsexposure
 * API for Analytics Exposure. Â© 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * AnalyticsExposureAPIFetchAnalyticsInformationApi.h
 *
 *
 */

#ifndef AnalyticsExposureAPIFetchAnalyticsInformationApi_H_
#define AnalyticsExposureAPIFetchAnalyticsInformationApi_H_

#include <pistache/http.h>
#include <pistache/http_headers.h>
#include <pistache/router.h>

#include <optional>
#include <string>
#include <utility>

#include "AnalyticsData.h"
#include "AnalyticsRequest.h"
#include "ProblemDetails.h"

namespace oai::nef::api {

class AnalyticsExposureAPIFetchAnalyticsInformationApi {
 public:
  explicit AnalyticsExposureAPIFetchAnalyticsInformationApi(
      const std::shared_ptr<Pistache::Rest::Router>& rtr);
  virtual ~AnalyticsExposureAPIFetchAnalyticsInformationApi() = default;
  void init();

  static const std::string base;

 private:
  void setupRoutes();

  void af_id_fetch_post_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void analytics_exposure_api_fetch_analytics_information_api_default_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);

  const std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during Parameter parsing
  /// and validation. May be overridden to return custom error formats. This is
  /// called inside a catch block. Important: When overriding, do not call
  /// `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleParsingException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during processing of the
  /// request in handler functions. May be overridden to return custom error
  /// formats. This is called inside a catch block. Important: When overriding,
  /// do not call `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleOperationException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Fetch analytics information
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="afId">Identifier of the AF</param>
  /// <param name="analyticsRequest"></param>
  virtual void af_id_fetch_post(
      const std::string& afId,
      const oai::nef::model::AnalyticsRequest& analyticsRequest,
      Pistache::Http::ResponseWriter& response) = 0;
};

}  // namespace oai::nef::api

#endif /* AnalyticsExposureAPIFetchAnalyticsInformationApi_H_ */
